language: python
python:
- '3.4'
- '3.5'
install:
- pip install cython
- pip install wheel
script:
- python setup.py build_ext -i
- python setup.py test
after_success:
- python setup.py bdist_wheel
- ls dist
before_deploy:
  - export RELEASE_PKG_WHL=$(ls ./dist/*.whl)
  - echo "deploying $RELEASE_PKG_WHL to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: fCc77zH6U3UeYgJLMyWSvJSuKqbPURKgGDosYD3F1ayaaCfU44RkZY1m54CdfEDFvqMfmhFcZJiCK9J1Rm3RHDfIcvfRqe8VsB/ehhQOvzfdzFeY6z5qOWw39smW9At2PeLQZ71AD/92cMZnJ9ueBmZOLTGYyG3yjqGSoaUoZo0=
  skip_cleanup: true
  overwrite: true
  file:
      - "${RELEASE_PKG_WHL}"
  on:
    repo: Ryex/Rabbyt
    tags: true
